#!/usr/bin/env bash

script_dir=$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)
dry_run="0"

while [[ $# > 0 ]]; do
  if [[ $1 == "--dry" ]]; then
    dry_run="1"
  fi
  shift
done

log() {
  if [[ $dry_run == "1" ]]; then
    echo "[DRY_RUN]: $1"
  else
    echo "$1"
  fi
}

execute() {
  log "execute $@"
  if [[ $dry_run == "1" ]]; then
    return
  fi

  "$@"
}


log "--------- dev-env ---------"