#!/usr/bin/env bash
dry_run="0"

while [[ $# > 0 ]]; do
  if [[ $1 == "--dry" ]]; then
    dry_run="1"
  fi
  shift
done

log() {
  if [[ $dry_run == "1" ]]; then
    echo "[DRY_RUN]: $@"
  else
    echo "$@"
  fi
}

execute() {
  log "execute $@"
  if [[ $dry_run == "1" ]]; then
    return
  fi

  "$@"
}

if [ -z "$XDG_CONFIG_HOME" ]; then
    echo "no xdg config home"
    echo "using ~/.config"
    XDG_CONFIG_HOME=$HOME/.config

    if [ ! -d $XDG_CONFIG_HOME ]; then
        execute mkdir -p $XDG_CONFIG_HOME
    fi
fi

copy_dir() {
  to=$2

  if [[ ! -d $to ]]; then
    execute mkdir -p $to
  fi

  pushd $1
  dirs=$(find . -mindepth 1 -maxdepth 1 -type d | cut -c 3-)
  for dir in $dirs; do
    execute rm -rf $to/$dir
    execute cp -r $dir $to/$dir
  done
  popd
}

copy_file() {
  from=$1
  to=$2
  name=$(basename $from)
  execute rm $to/$name
  execute cp $from $to/$name
}

log "--------- dev-env ---------"

copy_dir env/.config $XDG_CONFIG_HOME
copy_dir env/.local $HOME/.local
copy_file env/.zshrc $HOME
