#!/usr/bin/env bash

USER_ID=${LOCAL_USER_ID:-1000}
GROUP_ID=${LOCAL_GROUP_ID:-1000}

# Create the non root group
groupadd -g $GROUP_ID neodev
# Create the non root user
useradd -d /home/neodev -s /bin/zsh -u $USER_ID neodev -g $GROUP_ID

# Set home directory owner to new user 
chown -R neodev:neodev /home/neodev

exec gosu neodev "$@"
