#!/usr/bin/env bash

# check if AWS CLI is installed
if ! command -v aws &> /dev/null; then
  echo "AWS CLI is not installed."
  exit 1
fi

selected_profile=$(aws configure list-profiles | fzf)

# make sure a profile is selected
if [[ -z "$selected_profile" ]]; then
  echo "No profile selected."
  exit 1
fi

echo "Selected profile $selected_profile."

# check if the profile is already logged in
if aws sts get-caller-identity --profile "$selected_profile" &> /dev/null; then
  echo "Profile already authenticated."
  exit 0
fi

# start the login process
aws sso login --profile "$selected_profile"

# confirm login was successful
if ! aws sts get-caller-identity --profile "$selected_profile" &> /dev/null; then
  echo "Login failed."
  exit 1
fi

echo "Login successful."