#!/usr/bin/env bash

copy_dir() {
  from=$1
  to=$2

  pushd $from
  dirs=$(find . -mindepth 1 -maxdepth 1 -type d)
  for dir in $dirs; do
    execute rm -rf $to/$dir
    execute cp -r $dir $to/$dir
  done
  popd
}

copy_dir ../config $XDG_CONFIG_HOME
