name: "Build Image"

on:
  push:
    tags: ["base-v*"]
  pull_request:
    tags: ["base-v*"]

jobs:
  build:
    # Use a variable here to make simple workflows function
    # when using both Github and Gitea actions
    runs-on: ${{ vars.RUNS_ON }} 
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Massively slows down the build without much benefit currently
      # - name: Setup QEMU
      #   uses: docker/setup-qemu-action@v3
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }} 
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Extract Metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKER_REGISTRY }}${{ secrets.DOCKER_USERNAME }}/dev-env
          tags: |
            type=sha
            type=match,pattern=base-v(\d.\d.\d),group=1
            # type=semver,pattern=v{{version}}
            # type=semver,pattern=v{{major}}.{{minor}}
            # type=semver,pattern=v{{major}}
      - name: Build and Push
        id: push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }} 

