name: "Build Image"

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    # Use a variable here to make simple workflows function
    # when using both Github and Gitea actions
    runs-on: ${{ vars.RUNS_ON }} 
    steps:
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Massively slows down the build without much benefit currently
      # - name: Setup QEMU
      #   uses: docker/setup-qemu-action@v3
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }} 
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and Push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ secrets.DOCKER_REGISTRY }}${{ secrets.DOCKER_USERNAME }}/dev-env:latest
