name: "Build Go Image"

on:
  push:
    tags: ["gopsql-v*"]
  pull_request:
    tags: ["gopsql-v*"]

jobs:
  build:
    # Use a variable here to make simple workflows function
    # when using both Github and Gitea actions
    runs-on: ${{ vars.RUNS_ON }} 
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Massively slows down the build without much benefit currently
      # - name: Setup QEMU
      #   uses: docker/setup-qemu-action@v3
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }} 
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Extract Metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKER_REGISTRY }}${{ secrets.DOCKER_USERNAME }}/dev-gopsql
          tags: |
            type=sha
            type=match,pattern=gopsql-v(\d.\d.\d),group=1
      - name: Build and Push
        id: push
        uses: docker/build-push-action@v6
        with:
          push: true
          file: gopsql.dockerfile
          build-args: |
             BASE_IMAGE=${{ secrets.DOCKER_REGISTRY }}${{ secrets.DOCKER_USERNAME }}
          tags: ${{ steps.meta.outputs.tags }} 

